import { Car } from './types';

export const carsData: Car[] = [
  {
    id: 1,
    name: "Honda Civic RS 1.5 VTEC",
    brand: "Honda",
    model: "Civic RS",
    type: "Hatch",
    transmission: "CVT 7-Speed",
    seats: 5,
    fuel: "Bensin",
    cc: 1498,
    power: 178,
    torque: 240,
    drive: "FWD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 609500000,
    price_used: 480000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/8/83/2022_Honda_Civic_RS_1.5_FE2_%2820220706%29_01.jpg",
    description: "Hatchback sporti dengan mesin Turbocharger dan sistem keselamatan canggih Honda SENSING."
  },
  {
    id: 2,
    name: "Toyota Fortuner 2.8 VRZ GR-Sport",
    brand: "Toyota",
    model: "Fortuner VRZ GR-Sport",
    type: "SUV",
    transmission: "6-Speed AT",
    seats: 7,
    fuel: "Diesel",
    cc: 2755,
    power: 203,
    torque: 499,
    drive: "4WD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 726850000,
    price_used: 590000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/2021_Toyota_Fortuner_2.8_VRZ_2WD_GUN166_%2820220917%29.jpg",
    description: "SUV tangguh bersasis tangga (ladder frame) dengan torsi mesin diesel yang luar biasa dan penggerak 4 roda."
  },
  {
    id: 3,
    name: "Suzuki Ertiga Hybrid GX A/T",
    brand: "Suzuki",
    model: "Ertiga Hybrid GX",
    type: "MPV",
    transmission: "4-Speed AT",
    seats: 7,
    fuel: "Hybrid",
    cc: 1462,
    power: 105,
    torque: 138,
    drive: "FWD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 284600000,
    price_used: 215000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/53/2022_Suzuki_Ertiga_GL_1.5_NC22S_%2820221016%29.jpg",
    description: "MPV keluarga andal dengan teknologi Smart Hybrid Vehicle by Suzuki (SHVS) yang sangat efisien bahan bakar."
  },
  {
    id: 4,
    name: "Toyota Yaris 1.5 S CVT GR-Sport",
    brand: "Toyota",
    model: "Yaris GR-Sport",
    type: "Hatch",
    transmission: "CVT 7-Speed",
    seats: 5,
    fuel: "Bensin",
    cc: 1496,
    power: 107,
    torque: 140,
    drive: "FWD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 345000000,
    price_used: 285000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/30/2021_Toyota_Yaris_S_CVT_GR-Sport_MXPH10_%2820210827%29_01.jpg",
    description: "Hatchback lincah berjiwa muda hasil racikan divisi balap Gazoo Racing, lincah bermanuver di jalanan kota."
  },
  {
    id: 5,
    name: "Honda City Hatchback RS CVT",
    brand: "Honda",
    model: "City Hatchback RS",
    type: "Hatch",
    transmission: "CVT",
    seats: 5,
    fuel: "Bensin",
    cc: 1498,
    power: 121,
    torque: 145,
    drive: "FWD",
    year: 2022,
    mileage: 18000,
    condition: "used",
    price_new: 362500000,
    price_used: 279000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/2/22/2021_Honda_City_Hatchback_1.5_RS_GN5_%2820211116%29_01.jpg",
    description: "Hatchback serbaguna dengan akomodasi kabin ULTRA Seat legendaris yang fleksibel dan irit BBM."
  },
  {
    id: 6,
    name: "Toyota Avanza 1.3 E M/T",
    brand: "Toyota",
    model: "Avanza 1.3 E",
    type: "MPV",
    transmission: "5-Speed MT",
    seats: 7,
    fuel: "Bensin",
    cc: 1329,
    power: 98,
    torque: 121,
    drive: "FWD",
    year: 2022,
    mileage: 24000,
    condition: "used",
    price_new: 235100000,
    price_used: 195000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/2021_Toyota_Avanza_1.5_G_W101_%2820211231%29_01.jpg",
    description: "Mobil Sejuta Umat yang kini hadir dengan penggerak roda depan (FWD) dan kabin yang jauh lebih lega."
  },
  {
    id: 7,
    name: "Wuling Air EV Premium Long Range",
    brand: "Wuling",
    model: "Air EV Premium Long Range",
    type: "EV",
    transmission: "Automatic Single Reduction",
    seats: 4,
    fuel: "Electric",
    cc: 0,
    power: 41,
    torque: 110,
    drive: "RWD",
    year: 2023,
    mileage: 2500,
    condition: "used",
    price_new: 299500000,
    price_used: 215000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/77/2023_Wuling_Air_EV_Premium_Long_Range_%2820231109%29.jpg",
    description: "Kendaraan listrik kompak perkotaan terlaris dengan jarak tempuh hingga 300 km dalam sekali pengisian daya."
  },
  {
    id: 8,
    name: "Wuling Almaz RS 1.5T Pro",
    brand: "Wuling",
    model: "Almaz RS 1.5T Pro",
    type: "SUV",
    transmission: "CVT 8-Speed Simulation",
    seats: 7,
    fuel: "Bensin",
    cc: 1451,
    power: 140,
    torque: 250,
    drive: "FWD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 439200000,
    price_used: 310000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/2023_Wuling_Almaz_RS_Pro_1.5T_%2820231109%29.jpg",
    description: "SUV pintar yang dilengkapi teknologi berkendara semi-otonom ADAS dan sistem perintah suara berbahasa Indonesia (WIND)."
  },
  {
    id: 9,
    name: "Wuling Cloud EV 460km Premium",
    brand: "Wuling",
    model: "Cloud EV Premium",
    type: "EV",
    transmission: "Automatic Single Speed",
    seats: 5,
    fuel: "Electric",
    cc: 0,
    power: 136,
    torque: 150,
    drive: "FWD",
    year: 2024,
    mileage: 0,
    condition: "new",
    price_new: 438000000,
    price_used: 395000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/2/29/2024_Wuling_Cloud_EV_460_Premium_Range_%2820240726%29_01.jpg",
    description: "Hatchback premium bertenaga listrik murni dengan desain nyaman mengadopsi 'Sofa-Mode' di dalam interiornya."
  },
  {
    id: 10,
    name: "Wuling Binguo EV Premium 333km",
    brand: "Wuling",
    model: "Binguo EV Premium",
    type: "EV",
    transmission: "Automatic Single Speed",
    seats: 5,
    fuel: "Electric",
    cc: 0,
    power: 68,
    torque: 150,
    drive: "FWD",
    year: 2024,
    mileage: 0,
    condition: "new",
    price_new: 359000000,
    price_used: 320000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/08/2023_Wuling_BinguoEV_Premium_Range_%2820231109%29.jpg",
    description: "Gaya klasik retro ikonik yang dipadukan dengan kepraktisan modern tanpa emisi."
  },
  {
    id: 11,
    name: "Mercedes-Benz A200 Progressive Line",
    brand: "Mercedes",
    model: "A200",
    type: "Sedan",
    transmission: "7G-DCT Automatic",
    seats: 5,
    fuel: "Bensin",
    cc: 1332,
    power: 163,
    torque: 250,
    drive: "FWD",
    year: 2022,
    mileage: 15000,
    condition: "used",
    price_new: 855000000,
    price_used: 685000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/77/Mercedes-Benz_A_200_Sedan_Progressive_Line_FL3_IIMS_2024_02.jpg",
    description: "Sedan entry premium Jerman dengan mesin turbo kencang namun irit, serta sistem MBUX cerdas generasi terbaru."
  },
  {
    id: 12,
    name: "BMW 320i M Sport G20 LCI",
    brand: "BMW",
    model: "320i M Sport",
    type: "Sedan",
    transmission: "8-Speed Steptronic",
    seats: 5,
    fuel: "Bensin",
    cc: 1998,
    power: 184,
    torque: 300,
    drive: "RWD",
    year: 2023,
    mileage: 0,
    condition: "new",
    price_new: 1130000000,
    price_used: 920000000,
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/BMW_320i_M_Sport_FL_IIMS_2024_02.jpg",
    description: "Definisi sport sedan sejati dengan pengendalian presisi legendaris BMW, suspensi M Sport, dan layar melengkung Curved Display."
  }
];
